### ISSUE TITLE
Building a tensorflow custom operation just by changing its name in all files (.cc .cu BUILD) results in segmentation fault. 

### ISSUE THREAD

**Issue by MoussaMM** [tensorflow/custom-op#40]
the error happens only with gpu. i built the .so library with bazel using ubuntu16-gpu docker image. root@6d23afbfc05f:/home/sbs/my_op# python tensorflow_crop_and_resize1/python/ops/crop_and_resize1_ops.py
2019-11-28 15:28:50.468388: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-28 15:28:50.472866: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-11-28 15:28:50.475121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.815
pciBusID: 0000:01:00.0
2019-11-28 15:28:50.475137: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-28 15:28:50.475893: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-28 15:28:50.476576: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-11-28 15:28:50.476748: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-11-28 15:28:50.477763: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-11-28 15:28:50.478716: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-11-28 15:28:50.481232: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-28 15:28:50.481787: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-28 15:28:50.482261: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-28 15:28:50.506346: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-11-28 15:28:50.507012: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x60e19f0 executing computations on platform Host. Devices:
2019-11-28 15:28:50.507027: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-11-28 15:28:50.564176: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x61052a0 executing computations on platform CUDA. Devices:
2019-11-28 15:28:50.564202: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1660 Ti, Compute Capability 7.5
2019-11-28 15:28:50.564550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.815
pciBusID: 0000:01:00.0
2019-11-28 15:28:50.564582: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-28 15:28:50.564596: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-28 15:28:50.564607: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-11-28 15:28:50.564618: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-11-28 15:28:50.564629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-11-28 15:28:50.564639: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-11-28 15:28:50.564650: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-28 15:28:50.565124: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-28 15:28:50.760387: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-28 15:28:50.760411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-11-28 15:28:50.760416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-11-28 15:28:50.760997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3769 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-11-28 15:28:50.762516: I tensorflow/core/common_runtime/eager/execute.cc:574] Executing op CropAndResize1 in device /job:localhost/replica:0/task:0/device:GPU:0
2019-11-28 15:28:51.049562: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-11-28 15:28:51.049591: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1
Aborted (core dumped)

**Comment by MoussaMM** [comment]
The error is due to some unmet depencies with 'gpu_lib' while including gpu_event_manager.h. I built the op with tf_custom_op and elemenated th code using the event manager and it worked.
